/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import static Utils.JsonDataFetcher.SEND;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author BTF
 */
public class Career_Word_Key_JF2 extends javax.swing.JFrame {
    
    ArrayList<String[]> RSS;
    DefaultTableModel TablaCareer, TablaWordK;
    int SCR = -1, SWKR = -1;

    /**
     * Creates new form Career_Word_Key_JF2
     */
    public Career_Word_Key_JF2() {
        initComponents();
    }
    
    private void ObtenerDatos(String SS, String TT, String WW) {
        RSS = SEND(SS, TT, WW);
    }
    
    private void PintarTablaColumns() {
        String[] Carreras = {"ID", "Nombre", "Campus", "Descripcion"},
                Palabras = {"ID", "Palabra Clave"};
        TablaCareer = (DefaultTableModel) JTCareer.getModel();
        TablaCareer.setColumnCount(Carreras.length);
        TablaWordK = (DefaultTableModel) JTWordKey.getModel();
        TablaWordK.setColumnCount(Palabras.length);
        int count = 0;
        for (String CR : Carreras) {
            JTableHeader tableHeader = JTCareer.getTableHeader();
            TableColumnModel tableColumnModel = tableHeader.getColumnModel();
            TableColumn tableColumn = tableColumnModel.getColumn(count);
            tableColumn.setHeaderValue(CR);
            tableHeader.repaint();
            count++;
        }
        count = 0;
        for (String PAL : Palabras) {
            JTableHeader tableHeader = JTWordKey.getTableHeader();
            TableColumnModel tableColumnModel = tableHeader.getColumnModel();
            TableColumn tableColumn = tableColumnModel.getColumn(count);
            tableColumn.setHeaderValue(PAL);
            tableHeader.repaint();
            count++;
        }
    }
    
    private void PintarTablasRows(DefaultTableModel Tabla, Object id) {
        try {
            String ID=String.valueOf(id);
            Tabla.setRowCount(0);
            Object O[] = new Object[Tabla.getColumnCount()];
            ArrayList<String[]> Filler;
            String SS, TT, WW;
            if (O.length > 2) {
                SS = "c.id_career, c.`name`, cws.`name`, c.`description` ";
                TT = "ies9021_database.career c "
                        + "INNER JOIN ies9021_database.career_word_key cwk ON c.id_career = cwk.id_career "
                        + "INNER JOIN ies9021_database.campus_career AS ccc ON c.id_career = ccc.id_career "
                        + "INNER JOIN ies9021_database.campus AS cws ON ccc.id_campus = cws.id_campus ";
                WW = " cwk.id_word_key=" + ID + ";";
                Filler = SEND(SS, TT, WW);
            } else {
                SS = "wk.id_word_key, word";
                TT = "ies9021_database.words_key ";
                WW = "where word Like " + ID + ";";
                Filler = SEND(SS, TT, WW);
            }
            if (!Filler.isEmpty()) {
                for (int i = 0; i < Filler.size(); i++) {
                    System.arraycopy(Filler.get(i), 0, O, 0, Tabla.getColumnCount());
                }
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }
    
    private void LimpiarTablas(DefaultTableModel Tabla) {
        for (int i = Tabla.getRowCount() - 1; i >= 0; i--) {
            Tabla.removeRow(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TXTSearch = new javax.swing.JTextField();
        BTNSearch = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTWordKey = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTCareer = new javax.swing.JTable();
        JCBSearchType = new javax.swing.JComboBox<>();
        BTNWKSelect = new javax.swing.JButton();
        BTNDEL = new javax.swing.JButton();
        BTNADD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TXTSearch.setText("Palabra Clave");
        TXTSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TXTSearchFocusLost(evt);
            }
        });
        TXTSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTSearchKeyTyped(evt);
            }
        });

        BTNSearch.setText("Buscar");
        BTNSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSearchActionPerformed(evt);
            }
        });

        JTWordKey.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        JTWordKey.getTableHeader().setReorderingAllowed(false);
        JTWordKey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTWordKeyMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTWordKey);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        JTCareer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        JTCareer.getTableHeader().setReorderingAllowed(false);
        JTCareer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTCareerMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(JTCareer);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        JCBSearchType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empieza con", "Contiene", "Termina con" }));

        BTNWKSelect.setText("Selecionar");
        BTNWKSelect.setEnabled(false);
        BTNWKSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNWKSelectActionPerformed(evt);
            }
        });

        BTNDEL.setText("Borrar");
        BTNDEL.setEnabled(false);

        BTNADD.setText("Añadir");
        BTNADD.setEnabled(false);
        BTNADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNADDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TXTSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JCBSearchType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNSearch))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNWKSelect))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNADD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNDEL))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNSearch)
                    .addComponent(JCBSearchType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(BTNWKSelect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(BTNDEL)
                    .addComponent(BTNADD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTSearchFocusGained
        // TODO add your handling code here:
        if (TXTSearch.getForeground().equals(Color.lightGray)) {
            TXTSearch.setForeground(Color.black);
            TXTSearch.setText("");
            BTNSearch.setEnabled(true);
        }
    }//GEN-LAST:event_TXTSearchFocusGained

    private void TXTSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTSearchFocusLost
        // TODO add your handling code here:
        if (TXTSearch.getText().isBlank() || TXTSearch.getText().isEmpty()) {
            TXTSearch.setForeground(Color.lightGray);
            TXTSearch.setText("Palabra Clave");
            BTNSearch.setEnabled(false);
        }
    }//GEN-LAST:event_TXTSearchFocusLost

    private void TXTSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTSearchKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (TXTSearch.getText().length() >= 20) {
            evt.consume();
        } else {
            if (!(Character.isLetterOrDigit(c) || c == 8 || c == 32 || c == 127
                    || c == '\n' || c == '\t' || c == 44 || c == 46)) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_TXTSearchKeyTyped

    private void BTNSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSearchActionPerformed
        // TODO add your handling code here:
        if (!(TXTSearch.getText().isBlank() || TXTSearch.getText().isEmpty() || TXTSearch.getForeground().equals(Color.lightGray))) {
            String Search = TXTSearch.getText().toLowerCase();
            switch (JCBSearchType.getSelectedIndex()) {
                case 0:
                    Search = Search + "%";
                    break;
                case 1:
                    Search = "%" + Search + "%";
                    break;
                case 2:
                    Search = "%" + Search;
                    break;
                default:
                    break;
            }
            PintarTablasRows(TablaWordK, Search);
        }else{
            JOptionPane.showMessageDialog(this, "No se puede buscar la nada, escribe algo");
        }
    }//GEN-LAST:event_BTNSearchActionPerformed

    private void JTWordKeyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTWordKeyMouseClicked
        // TODO add your handling code here:
        if(JTWordKey.getSelectedRow()!=SWKR){
            BTNWKSelect.setEnabled(true);
            SWKR=JTWordKey.getSelectedRow();
        }
    }//GEN-LAST:event_JTWordKeyMouseClicked

    private void BTNWKSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNWKSelectActionPerformed
        // TODO add your handling code here:
        BTNWKSelect.setEnabled(false);
        PintarTablasRows(TablaCareer, TablaWordK.getValueAt(JTWordKey.getSelectedRow(), 0));
        
    }//GEN-LAST:event_BTNWKSelectActionPerformed

    private void JTCareerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTCareerMouseClicked
        // TODO add your handling code here:
        if(JTCareer.getSelectedRow()!=SCR){
            SCR=JTCareer.getSelectedRow();
            BTNADD.setEnabled(true);
            BTNDEL.setEnabled(true);
        }
    }//GEN-LAST:event_JTCareerMouseClicked

    private void BTNADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNADDActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BTNADDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Career_Word_Key_JF2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Career_Word_Key_JF2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Career_Word_Key_JF2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Career_Word_Key_JF2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Career_Word_Key_JF2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNADD;
    private javax.swing.JButton BTNDEL;
    private javax.swing.JButton BTNSearch;
    private javax.swing.JButton BTNWKSelect;
    private javax.swing.JComboBox<String> JCBSearchType;
    private javax.swing.JTable JTCareer;
    private javax.swing.JTable JTWordKey;
    private javax.swing.JTextField TXTSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
