/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import Utils.JsonDataFetcher;
import static Utils.JsonDataFetcher.selectQuery;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author BTF
 */
public class CodeTester extends javax.swing.JFrame {

    /**
     * Creates new form CodeTester
     */
    public CodeTester() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTN = new javax.swing.JButton();
        TXAWordK = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BTN.setText("TestCode");
        BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNActionPerformed(evt);
            }
        });

        TXAWordK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXAWordKKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TXAWordK, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TXAWordK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNActionPerformed
        // TODO add your handling code here:
        //String SS="*",FF="ies9021_database.career",WW="id_career<300";
//        String TokenI="1A2B3C",Email="brunoloco63@gmail.com";
//        String Select="id_user, `name`,Last_token='"+TokenI+"' AS 'correcttoken', ((select minute_token from ies9021_database.settings ) > timestampdiff(minute,f_token,current_time())) AS 'tokenvalid'",
//                    Tabla="ies9021_database.users",
//                    Where=("email='"+Email.toLowerCase()+"' LIMIT 5;");
//        //List<String> RSL = selectQuery(SS, FF, WW);
//        List<String[]> RSL = selectQuery(Select,Tabla,Where);
//        for (String[] st : RSL) {
//            System.out.println(Arrays.toString(st));
//        }
//        ArrayList<String[]> RSO = JsonDataFetcher.SEND(Select, Tabla, Where);
//        for (String[] OT : RSO) {
//            System.out.println(Arrays.toString(OT));
//        }
//        System.out.println(RSO.get(0)[0]);//id
//        System.out.println(RSO.get(0)[1]);//name
//        System.out.println(RSO.get(0)[2]);//Token
//        System.out.println(RSO.get(0)[3]);//Limite Tiempo
        String Alfa=",andres,alejandro,xd,,s,e,,w,";
        if(Alfa.charAt(0)==44){Alfa=Alfa.substring(1);}
        String[] TXA = Alfa.replaceAll(",,", ",").split(",");
        
            System.out.println("TXA = "+TXA.length);
            for (int i = 0; i < TXA.length; i++) {
                TXA[i]=TXA[i].trim();
            }
            System.out.println("TXAx = "+TXA.length);
            System.out.println(Arrays.toString(TXA));
        System.out.println(Arrays.toString(Arrays.stream(Alfa.split("\\s*,\\s*")).filter(part->!part.isEmpty()).toArray(String[]::new)));
        this.dispose();
    }//GEN-LAST:event_BTNActionPerformed

    private void TXAWordKKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXAWordKKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String TXA=TXAWordK.getText();
        if (!(Character.isAlphabetic(c) || c == 8 || c == 127
            || c == 44 || c == '\t' || c == 9)) {
            evt.consume();
        }
        else if(c==44&&TXA.contains(",,")){
            TXAWordK.setText(TXA.replace(",,", ",")+",");
            evt.consume();}
        if(TXA.contains(",,")){TXAWordK.setText(TXA.replaceAll(",,", ","));}
        System.out.println((c==44&&(TXA.contains(",,")||TXA.contains(" ,"))));
    }//GEN-LAST:event_TXAWordKKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CodeTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CodeTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CodeTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CodeTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CodeTester().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN;
    private javax.swing.JTextField TXAWordK;
    // End of variables declaration//GEN-END:variables
}
