/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import Utils.General_Methods;
import static Utils.TokenSender.SendMessage;

/**
 *
 * @author BTF
 */
public class InicioJF extends javax.swing.JFrame {

    /**
     * Creates new form InicioJF
     */
    General_Methods GEM;
            
    
    public InicioJF() {
        initComponents();
        GEM= new General_Methods();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BTNIngresar = new javax.swing.JButton();
        TXTEmail = new javax.swing.JTextField();
        BTNTokenSender = new javax.swing.JButton();
        TXTToken = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");

        jLabel1.setFont(new java.awt.Font("Lucida Console", 0, 24)); // NOI18N
        jLabel1.setText("Mi Carrera Perfecta");

        BTNIngresar.setText("Ingresar");
        BTNIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNIngresarActionPerformed(evt);
            }
        });

        TXTEmail.setForeground(Color.lightGray);
        TXTEmail.setText("E-mail");
        TXTEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TXTEmailFocusLost(evt);
            }
        });
        TXTEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTEmailKeyTyped(evt);
            }
        });

        BTNTokenSender.setText("Pedir Token");
        BTNTokenSender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNTokenSenderActionPerformed(evt);
            }
        });

        TXTToken.setForeground(Color.lightGray);
        TXTToken.setText("Token");
        TXTToken.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTTokenFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TXTTokenFocusLost(evt);
            }
        });
        TXTToken.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTTokenKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TXTEmail)
                        .addComponent(TXTToken)
                        .addComponent(BTNTokenSender, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(TXTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNTokenSender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTToken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTNIngresar)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTEmailFocusGained
        // TODO add your handling code here:
        if(TXTEmail.getForeground().equals(Color.lightGray)){
            TXTEmail.setForeground(Color.BLACK);
            TXTEmail.setText("");
        }
    }//GEN-LAST:event_TXTEmailFocusGained

    private void TXTEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTEmailFocusLost
        // TODO add your handling code here:
        if(TXTEmail.getText().isEmpty()||TXTEmail.getText().isBlank()){
            TXTEmail.setForeground(Color.lightGray);
            TXTEmail.setText("E-mail");
        }
    }//GEN-LAST:event_TXTEmailFocusLost

    private void BTNIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNIngresarActionPerformed
        // TODO add your handling code here:
        try{
            if(TXTEmail.getForeground().equals(Color.BLACK)){
                if(GEM.Inicio(TXTEmail.getText(),TXTToken.getText(),this)){
                    Tablon_JF TJF = new Tablon_JF(GEM);
                    this.setVisible(false);
                    TJF.setVisible(true);
                    this.dispose();
                }
            }else{
                JOptionPane.showMessageDialog(this,"Faltan datos");
            }
        }catch(HeadlessException e){
            System.out.println("Error in: "+this.getName()
                    + "Sector: InicioJF\nError: "+e.getMessage());
        }
    }//GEN-LAST:event_BTNIngresarActionPerformed

    private void BTNTokenSenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNTokenSenderActionPerformed
        // TODO add your handling code here:
        try{
        if(TXTEmail.getForeground().equals(Color.BLACK)){
            String X=GEM.Existe(TXTEmail.getText());
            switch(X.charAt(0)){//GEM.Existe(TXTEmail.getText()) cambiarlo de Booean a Int
                case '2': JOptionPane.showMessageDialog(this, "No se encuentra registrado su Email");
                    break;
                case '0': JOptionPane.showMessageDialog(this,
                  "Su Email ha sido deshabilitado\nPor favor, contacte a Soporte");
                    break;
                case '1': SendMessage(TXTEmail.getText(),X.substring(1));
                    break;
                default:
                    JOptionPane.showMessageDialog(this,
              "Hemos tenido un problema\nPor favor, contacte a Soporte, o intente mas tarde");
                    break;
            }
//            if(GEM.Existe(TXTEmail.getText())){
//                GEM.SendMessage(TXTEmail.getText());
//            }else{
//            JOptionPane.showMessageDialog(this,"Email Invalido");
//            }
        
        BTNTokenSender.setEnabled(false);
        BTNTokenSender.setText("Cargando");
        Timer timer = new Timer(10000, (ActionEvent e) -> {
            BTNTokenSender.setEnabled(true); // Habilitar el botón después de 10 segundos
            BTNTokenSender.setText("Token >");
            ((Timer) e.getSource()).stop(); // Detener el temporizador
        });

                timer.start(); // he iniciado el timer
        
        }else{
            JOptionPane.showMessageDialog(this,"No se ha ingresado ningun correo");
        }
        }catch(HeadlessException e){
            System.out.println("Error in: "+this.getName()
                    + "Sector: BTNTokenSender\nError: "+e.getMessage());
        }



    }//GEN-LAST:event_BTNTokenSenderActionPerformed

    private void TXTTokenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTTokenFocusGained
        // TODO add your handling code here:
        if(TXTToken.getForeground().equals(Color.lightGray)){
            TXTToken.setForeground(Color.black);
            TXTToken.setText(null);
        }
    }//GEN-LAST:event_TXTTokenFocusGained

    private void TXTTokenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTTokenFocusLost
        // TODO add your handling code here:
        if(TXTToken.getText().isEmpty()){
            TXTToken.setForeground(Color.lightGray);
            TXTToken.setText("Token");
        }
    }//GEN-LAST:event_TXTTokenFocusLost

    private void TXTTokenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTTokenKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(TXTToken.getText().length()>=6){
            evt.consume();
        }else {
            if(!(Character.isLetterOrDigit(c) || c == 8 || c == 127 
                    || c == '\n' || c == '\t')){
                evt.consume();
                JOptionPane.showMessageDialog(this,"Solo se permiten numeros y letras");
            }
        }
    }//GEN-LAST:event_TXTTokenKeyTyped

    private void TXTEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTEmailKeyTyped
        // TODO add your handling code here:
        
        char c = evt.getKeyChar();
        if(TXTEmail.getText().length()>=120){
            evt.consume();
        }else {
            if(!(Character.isLetterOrDigit(c) || c == '@' || c == '.' 
                    || c == '-' || c == '_' || c == 8 || c == 127 || c == '\t')){
                evt.consume();
            }
        }
    }//GEN-LAST:event_TXTEmailKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNIngresar;
    private javax.swing.JButton BTNTokenSender;
    private javax.swing.JTextField TXTEmail;
    private javax.swing.JTextField TXTToken;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
